/*
 * Copyright 2015 Felipe Santos <live.proto at hotmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package proto.cederj.prownloader.mvp.view.swing;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import proto.cederj.prownloader.mvp.view.CourseView;
import proto.cederj.prownloader.mvp.view.MainView;
import proto.cederj.prownloader.util.DateUtil;

/**
 *
 * @author Felipe Santos <live.proto at hotmail.com>
 */
public class CoursePanelSwing extends javax.swing.JPanel implements CourseView {

    private long modelId;
    private MainView mainView;

    /**
     * Creates new form Course
     */
    public CoursePanelSwing(MainView view) {
        this.mainView = view;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        labelLessonsAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelProfessors = new javax.swing.JLabel();
        btnOpenFolder = new javax.swing.JButton();
        btnUpdateMetada = new javax.swing.JButton();
        btnDownloadVideo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelFolder = new javax.swing.JLabel();
        labelLastMetadataUpdate = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("professor_list");

        setPreferredSize(new java.awt.Dimension(500, 300));

        //labelCourseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCourseName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCourseName.setText("Nome do Curso");

        //labelLessonsAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLessonsAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLessonsAmount.setText("0 aulas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Professores");

        //labelProfessors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelProfessors.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelProfessors.setText("Fulano, Ciclano, Beltrano");

        btnOpenFolder.setText("Abrir pasta");
        btnOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOpenFolder(evt);
            }
        });

        btnUpdateMetada.setText("Atualizar metadados");
        btnUpdateMetada.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUpdateMetadata(evt);
            }
        });

        btnDownloadVideo.setText("Baixar vídeo-aulas");
        btnDownloadVideo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDownloadVideo(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Operações");

        labelFolder.setText("..\\..\\curso");

        labelLastMetadataUpdate.setText("atualizado em 20/01/2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourseName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelLessonsAmount)
                                        .addGap(31, 31, 31))
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addComponent(labelProfessors))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(btnDownloadVideo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnUpdateMetada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnOpenFolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(labelFolder)
                                                                .addComponent(labelLastMetadataUpdate))))
                                        .addContainerGap(68, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLessonsAmount)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourseName)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelProfessors)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnOpenFolder)
                                .addComponent(labelFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUpdateMetada)
                                .addComponent(labelLastMetadataUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDownloadVideo)
                        .addGap(22, 22, 22))
        );

    }// </editor-fold>//GEN-END:initComponents

    private void onUpdateMetadata(java.awt.event.ActionEvent evt) {
        mainView.onDownloadCourseMetadata(modelId);
    }

    private void onDownloadVideo(java.awt.event.ActionEvent evt) {
        mainView.onDownloadCourseVideoFile(modelId);
    }

    private void onOpenFolder(java.awt.event.ActionEvent evt) {
        mainView.onOpenFolder(modelId);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFolder;
    private javax.swing.JButton btnUpdateMetada;
    private javax.swing.JButton btnDownloadVideo;
    private javax.swing.JLabel labelCourseName;
    private javax.swing.JLabel labelLessonsAmount;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelProfessors;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelFolder;
    private javax.swing.JLabel labelLastMetadataUpdate;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setCourseId(long id) {
        modelId = id;
    }

    @Override
    public void setCourseName(String name) {
        labelCourseName.setText(name);
    }

    @Override
    public void setCourseLessonsAmount(int count) {
        String lesson = count + " aula";
        if (count > 1) {
            lesson = lesson + "s";
        }
        labelLessonsAmount.setText(lesson);
    }

    @Override
    public void setCourseProfessors(List<String> professors) {
        if (professors != null && !professors.isEmpty()) {
            StringBuilder builder = new StringBuilder();
            List<String> pro = new ArrayList<>(professors);
            builder.append(pro.remove(0));
            for (String s : pro) {
                builder.append(", ");
                builder.append(s);
            }
            labelProfessors.setText(builder.toString());
        }
    }

    @Override
    public void setCourseFolder(String folder) {
        labelFolder.setText(folder);
    }

    @Override
    public void setCourseMetadataLastUpdate(Calendar calendar) {
        DateUtil du = new DateUtil();
        labelLastMetadataUpdate.setText(du.generate(calendar));
    }

    @Override
    public void setCourseVideoDownloadDate(Calendar calendar) {
    }
}
